version: 2

sources:
    - name: scd
      description: scd dimension tables
      database: scd
      schema: dimensions
      tables:
          - name: customer_history

    - name: stripe
      description: stripe raw tables
      database: raw
      schema: stripe
      tables:
          - name: payment
            description: O
            
    - name: jaffle_shop
      description: jaffle_shop raw tables
      database: raw
      schema: jaffle_shop
      tables:
          - name: customers
            description: One record per customer.
            columns:
              - name: id
                tests:
                  - unique
                  - not_null
          - name: orders
            description: One record per order. Includes canceled and deleted orders.
            columns:
              - name: id
                tests:
                  - unique
                  - not_null
            